* Casual
A collection of opinionated [[https://github.com/magit/transient][Transient]]-based user interfaces for Emacs.

*THIS PROJECT IS WIP.*

Looking for Casual Calc? Go to https://github.com/kickingvegas/casual-calc

* Motivation
Emacs has many commands that are easy to forget if not used frequently. Menus are a user interface (UI) affordance that offers discoverability and recognition that can lower its learning curve. While menus are commonly associated with mouse-driven UI, the inclusion of Transient in Emacs core allows for building a keyboard-driven menu UI. Casual endeavors to offer this as many Emacs users prefer keyboard-driven workflows.

** Goals
- To provide a keyboard-driven menu UI toolkit for common Emacs editing commands.
- To provide casual access to the above commands.

** Non-Goals
- Full coverage of all Emacs editing commands. Casual is not intended to be a power user tool nor is it intended to be a replacement for mouse-driven menus.
- Strict adherence to Emacs editing command naming. While Casual is *mostly* in alignment with Emacs command naming, there are cases where it will make an opinionated change if the name is deemed too vague or idiomatic.
- UX Stability (for now). Given that Casual is early in its life-cycle, expect changes to its user experience in terms of menu hierarchy and keybinding choices in future releases.

* Requirements
Casual requires usage of
- Emacs ≥ 29.1
- Magit ≥ 4.0.0
- Casual Lib ≥ 1.1.0
  
Casual has been verified with the following configuration. 
- Emacs 29.4 (macOS 14.5, Ubuntu Linux 22.04.4 LTS)

* Asks
As Casual is new, we are looking for early adopters! Your [[https://github.com/kickingvegas/casual-symbol-overlay/discussions][feedback]] is welcome as it will likely impact Casual's evolution, particularly with regards to UI.

* Install

** A Note on Package Dependencies
Casual requires Casual Lib which in turn requires a recent installation of Transient 0.6.0+ from either [[https://elpa.gnu.org/packages/transient.html][ELPA]] or [[https://melpa.org/#/transient][MELPA]]. As an older version of Transient is built-in to the Emacs release, the package manager ~package.el~ will /not/ update this package unless the customizable variable ~package-install-upgrade-built-in~ is set to ~t~. Set this variable and proceed with installing Casual. Alternately invoking ~package-install~ with a prefix (~C-u~) will temporarily coerce the update of the built-in package. (example: ~C-u M-x package-install~ ~casual-editkit~)

As Transient is closely tied to Magit, installing the latest version of Magit (via [[https://elpa.nongnu.org/nongnu/magit.html][non-GNU ELPA]] or [[https://melpa.org/#/magit][MELPA]]) before installing Casual can also pick up the latest version of Transient.

* Common Menu Actions
Casual is built using Transient menus and as such adopts its default behavior.

Each menu item has a /key/ and a /label/. The /key/ is what is typed by the user to select the menu item. A key can be prefixed with a meta (M-) or control (C-) key.

Transient supports nested menus. Exiting a menu can be done in two ways:
- ~C-g~ will exit the current sub-menu and return you back to its parent menu.
- ~C-q~ will exit you completely from a Transient menu stack.

If a mouse is available, a menu item can be selected by moving the mouse cursor over its label and pressing down button 1.

Pressing the ~?~ key or ~C-h~ will toggle help for all the menu items. Press the key of interest to get help for it.

When a Transient menu is raised, a prefix argument (~C-u~) and an optional argument can be entered before selecting a menu item.

* Development
For users who wish to help contribute to Casual or personally customize it for their own usage, please read the [[docs/developer.org][developer documentation]].

* Sponsorship
If you enjoy using Casual, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]

* See Also
Casual is part of a suite of user interfaces for different Emacs packages called [[https://github.com/kickingvegas/casual-suite][Casual Suite]].

* Acknowledgments
A heartfelt thanks to all the contributors to Emacs, [[https://github.com/magit/transient][Transient]], Org Mode, and Magit. This package would not be possible without your efforts.

